version: '3.2'

volumes:
  build_21.2:
  build_21.3:
  build_22.3:

services:
  test-21.2:
    build: containers/1.9.4_erlang-21.2
    volumes:
    - .:/code
    - build_21.2:/code/_build
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test-21.3:
    build: containers/1.9.4_erlang-21.3
    volumes:
    - .:/code
    - build_21.3:/code/_build
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test-22.3:
    build: containers/1.9.4_erlang-22.3
    volumes:
    - .:/code
    - build_22.3:/code/_build
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka1:
    hostname: kafka1
    image: wurstmeister/kafka:0.11.0.1
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
