version: '3.2'

volumes:
  build__v1.9.4_20.3:
  deps__v1.9.4_20.3:
  build__v1.9.4_21.1:
  deps__v1.9.4_21.1:
  build__v1.9.4_21.2:
  deps__v1.9.4_21.2:
  build__v1.9.4_21.3:
  deps__v1.9.4_21.3:
  build__v1.9.4_22.1:
  deps__v1.9.4_22.1:
  build__v1.9.4_22.2:
  deps__v1.9.4_22.2:
  build__v1.9.4_22.3:
  deps__v1.9.4_22.3:

services:
  test_v1.9.4_20.3:
    build:
      context: ./
      args: ['ELIXIR_VERSION=v1.9.4', 'OTP_VERSION=20.3']
    volumes:
    - .:/code
    - build__v1.9.4_20.3:/code/_build
    - deps__v1.9.4_20.3:/code/deps
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test_v1.9.4_21.1:
    build:
      context: ./
      args: ['ELIXIR_VERSION=v1.9.4', 'OTP_VERSION=21.1']
    volumes:
    - .:/code
    - build__v1.9.4_21.1:/code/_build
    - deps__v1.9.4_21.1:/code/deps
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test_v1.9.4_21.2:
    build:
      context: ./
      args: ['ELIXIR_VERSION=v1.9.4', 'OTP_VERSION=21.2']
    volumes:
    - .:/code
    - build__v1.9.4_21.2:/code/_build
    - deps__v1.9.4_21.2:/code/deps
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test_v1.9.4_21.3:
    build:
      context: ./
      args: ['ELIXIR_VERSION=v1.9.4', 'OTP_VERSION=21.3']
    volumes:
    - .:/code
    - build__v1.9.4_21.3:/code/_build
    - deps__v1.9.4_21.3:/code/deps
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test_v1.9.4_22.1:
    build:
      context: ./
      args: ['ELIXIR_VERSION=v1.9.4', 'OTP_VERSION=22.1']
    volumes:
    - .:/code
    - build__v1.9.4_22.1:/code/_build
    - deps__v1.9.4_22.1:/code/deps
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test_v1.9.4_22.2:
    build:
      context: ./
      args: ['ELIXIR_VERSION=v1.9.4', 'OTP_VERSION=22.2']
    volumes:
    - .:/code
    - build__v1.9.4_22.2:/code/_build
    - deps__v1.9.4_22.2:/code/deps
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

  test_v1.9.4_22.3:
    build:
      context: ./
      args: ['ELIXIR_VERSION=v1.9.4', 'OTP_VERSION=22.3']
    volumes:
    - .:/code
    - build__v1.9.4_22.3:/code/_build
    - deps__v1.9.4_22.3:/code/deps
    working_dir: /code
    command: tail -f /dev/null
    depends_on:
      - kafka1

