version: '3.2'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka1:
    hostname: kafka1
    image: wurstmeister/kafka:0.11.0.1
    depends_on:
      - zookeeper
    volumes:
      - ./ssl:/ssl
    env_file: docker-compose-kafka.env
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka1
